### ISSUE TITLE
KWS

### ISSUE THREAD

**Issue by tugstugi** [linto-ai/linto-command-module#1]
Is there a pretrained KWS model which can be used with this repo? If not, how can I train one?

**Comment by damienlaine** [comment]
Here's a model for the "LinTO" KeyWord : https://github.com/linto-ai/linto-models

You can also train your own models with the provided tool : https://github.com/linto-ai/HMG
we're still ought to provide the necessary documention though. I suggest you to watch our repos for upcoming releases which will occur very soon.
