### ISSUE TITLE
Community Forum

### ISSUE THREAD

**Issue by StuartIanNaylor** [linto-ai/linto-command-module#3]
Hi really like what you guys are doing downloaded the https://gamma.linto.ai/downloads/Raspberry/v1.1/linto-maker-buster-v1.1-seeedvoicecard.img

To find a smiley face that does little.
It took some searching to find lintoOS is pi:pi login:password but still stuck as the seed2miccard isn't recognised by aplay -l or pacmd list-cards as pulse is not running.

I will probably get there but a forum is usually a vast source of info and rather than posting here where it should be code related questions I would have somewhere to quickly get up to speed with Linto.

Without a forum I hit a cul-de-sac and its only persistance that I post here and apols for that but there isn't anywhere else.
I think this might not just be me and a forum would be really beneficial as a community of support would emerge and documentation without it always needing to be by the core team.

I have been using Mycroft and Rhasspy but the manner of your project really interests me and have been thinking along the same lines about datasets. (rolyantrauts just my name backwards)
https://community.rhasspy.org/t/kws-small-lean-and-just-enough-for-fit-for-purpose/968

I am really interested in the Keyword datasets and maybe able to get much going in a English repo but very interested in your thoughts on regional and gender datsets where I have been extracting words from.
https://openslr.org/83/

Also with TPU hourly server hosting much bigger datasets (accurate) could be processed without need of user hardware.
My GTX780 does its best but many don't even have that and don't need to and beginning to wonder if we will see batched model processing via TPU hosting as its actually really cheap maybe via a minium donation mode.

https://cloud.google.com/tpu/pricing?hl=ru

It might be possible to batch a few models in an hour maybe, if that was backed by a dataset query database and custom upload model processing services could be an extremely vialable option that is extremely beneficial for many.

The most accurate models are custom trained and weighted to regional and gender demographics and that could be provided easily and cost effectively with great benefit.

**Comment by Lokhozt** [comment]
Hello Stuart, 
Thank you for your input.
For the image configuration i invite you to reach to the documentation on [linto.ai](https://linto.ai/).
Regarding the forum, as an open-source project, it is our goal to embrace the community. The project is still young and changing rapidly and our focus is to improve the reliability and the core functionalities first. We are in the process of including means to communicate with the enthusiasts.
In the mean time the [documentation](https://doc.linto.ai/#/) is available on [github](https://github.com/linto-ai/documentation-website) and issue can be posted there.
The smiley face does nothing indeed and need to be connected to the remote server.
Concerning the dataset (which is partially [publicly collected](https://wakemeup.linto.ai/)) we will release it on the documentation website in the coming next weeks as we were reflecting on the matters of intellectual property and privacy.
For the training part for the models, i agree that improvements can be made and it might be a service that we will provide in the future.
